AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudwatch
Parameters:
  DashboardName:
    Description: The name of the dashboard
    Type: String
  Instanceidentity:
    Description: The EC2 instance ID to associate this alarm with.
    Type: AWS::EC2::Instance::Id
  Instanceidentity2:
    Description: The EC2 instance ID to associate this alarm with.
    Type: AWS::EC2::Instance::Id
  Instanceidentity3:
    Description: The EC2 instance ID to associate this alarm with.
    Type: AWS::EC2::Instance::Id
Resources:
  RecoveryTestAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Trigger a recovery when instance status check fails for 15
        consecutive minutes.
      Namespace: AWS/EC2
      MetricName: StatusCheckFailed_System
      Statistic: Minimum
      Period: '60'
      EvaluationPeriods: '15'
      ComparisonOperator: GreaterThanThreshold
      Threshold: '0'
      AlarmActions: [ !Sub "arn:aws:automate:eu-west-1:ec2:recover" ]
      Dimensions:
      - Name: InstanceId
        Value:
          Ref: Instanceidentity
          Ref: Instanceidentity2
          Ref: Instanceidentity3
  DashboardCloudwatch:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: amine-eks-cluster-cloudwatch-dashboard
      DashboardBody: {"Fn::Join":["",['{"widgets":[{"type":"metric","x":0,"y":0,"width":24,"height":6,"properties":{"metrics":[["AWS/EC2","CPUUtilization","InstanceId","',{Ref: Instanceidentity},'"],["AWS/EC2","CPUUtilization","InstanceId","',{Ref: Instanceidentity2},'"],["AWS/EC2","CPUUtilization","InstanceId","',{Ref: Instanceidentity3},'"]],"period":300,"stat":"Average","region":"eu-west-1","title":"EC2 Instance CPU"}},{"type":"metric","x":0,"y":0,"width":24,"height":6,"properties":{"metrics":[["AWS/EC2","NetworkIn","InstanceId","',{Ref: Instanceidentity},'"],["AWS/EC2","NetworkIn","InstanceId","',{Ref: Instanceidentity2},'"],["AWS/EC2","NetworkIn","InstanceId","',{Ref: Instanceidentity3},'"]],"period":300,"stat":"Average","region":"eu-west-1","title":"EC2 Instance NetworkIn"}},{"type":"metric","x":0,"y":0,"width":24,"height":6,"properties":{"metrics":[["AWS/EC2","NetworkOut","InstanceId","',{Ref: Instanceidentity},'"],["AWS/EC2","NetworkOut","InstanceId","',{Ref: Instanceidentity2},'"],["AWS/EC2","NetworkOut","InstanceId","',{Ref: Instanceidentity3},'"]],"period":300,"stat":"Average","region":"eu-west-1","title":"EC2 Instance NetworkOut"}}]}']]}
  CPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: CPU alarm for my instance
      #AlarmActions:
      #- !Ref Subscription
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: '60'
      EvaluationPeriods: '3'
      Threshold: '90'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: InstanceId
        Value:
          Ref: "Instanceidentity"
          Ref: "Instanceidentity2"
          Ref: "Instanceidentity3"
    